# Generated by Django 3.0 on 2021-11-17 01:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('type', models.CharField(choices=[('AM', 'American'), ('MX', 'Mexican'), ('CH', 'Chinese'), ('KR', 'Korean'), ('JP', 'Japanese'), ('IT', 'Italian'), ('VN', 'Vietnamese'), ('IN', 'Indian'), ('GR', 'Greek'), ('FR', 'French'), ('MD', 'Mediterranean'), ('CF', 'Cafe'), ('FF', 'Fast Food')], default='AM', max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField(blank=True, default='')),
                ('photos', models.TextField(blank=True, default='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
