# Generated by Django 2.2.24 on 2021-11-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodplace',
            name='type',
            field=models.CharField(choices=[('AM', 'American'), ('MX', 'Mexican'), ('CH', 'Chinese'), ('KR', 'Korean'), ('JP', 'Japanese'), ('IT', 'Italian'), ('VN', 'Vietnamese'), ('IN', 'Indian'), ('GR', 'Greek'), ('FR', 'French'), ('MD', 'Mediterranean'), ('CF', 'Cafe'), ('FF', 'Fast Food'), ('OT', 'Other')], default='AM', max_length=200),
        ),
    ]
